version: "3.0"

services:
  api:
    container_name: "rag-chat-api"
    volumes:
      - ./src/rag_chat_backend:/rag_chat_backend
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - PYTHONPATH=/
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_BASE_ENDPOINT=${AZURE_OPENAI_BASE_ENDPOINT}
      - AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME}
      - AZURE_OPENAI_LLM_DEPLOYMENT_NAME=${AZURE_OPENAI_LLM_DEPLOYMENT_NAME}
      - AZURE_OPENAI_LLM_MODEL_NAME=${AZURE_OPENAI_LLM_MODEL_NAME}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000

  db:
    container_name: "rag-chat-db"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      interval: 5s
      retries: 10
    ports:
      - 3306:3306
